Models/DataModels/Incident.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace TicketHandler.Models.DataModels
{
    public class Incident
    {
        public int Id { get; set; }

        // Incident settings
        [Display(Name = "Prio.")]
        public int? IncidentPriorityId { get; set; }
        [Display(Name = "Priority")]
        [ForeignKey("IncidentPriorityId")]
        public IncidentPriority IncidentPriority { get; set; }

        [Display(Name = "Status")]
        public int? IncidentStatusId { get; set; }
        [Display(Name = "Status")]
        [ForeignKey("IncidentStatusId")]
        public IncidentStatus IncidentStatus { get; set; }

        [Display(Name = "Type")]
        public int? IncidentTypeId { get; set; }
        [Display(Name = "Type")]
        [ForeignKey("IncidentTypeId")]
        public IncidentType IncidentType { get; set; }

        //Incident orgin

        [Display(Name = "INC#")]
        public string IncidentNumber { get; set; }

        [Display(Name = "Created")]
        public DateTime? Created { get; set; }

        [Display(Name = "Creator")]
        public int? PersonId { get; set; }
        [Display(Name = "Creator")]
        [ForeignKey("PersonId")]
        public Person Creator { get; set; }

        //Incident Location
        [Display(Name = "Site")]
        public int? SiteId { get; set; }
        [Display(Name = "Site")]
        [ForeignKey("SiteId")]
        public Site Site { get; set; }

        //Incident Handling
        [Display(Name = "Received")]
        public DateTime? Received { get; set; }

        [Display(Name = "Receiver")]
        public int? PersonId1 { get; set; }
        [Display(Name = "Receiver")]
        [ForeignKey("PersonId1")]
        public Person Receiver { get; set; }

        // Scheduling and assignment
        [Display(Name = "FE Scheduled")]
        public DateTime? FEScheduled { get; set; }

        [Display(Name = "FE Assigned")]
        public int? PersonId2 { get; set; }
        [Display(Name = "FE Assigned")]
        [ForeignKey("PersonId2")]
        public Person FEAssigned { get; set; }

        //Incident Description
        [Display(Name = "Description")]
        public string Description { get; set; }

        ////Incident Logg
        ///
        //[Display(Name = "FE Enters Site")]
        //public DateTime? FEEntersSite { get; set; }

        //[Display(Name = "FE Exits Site")]
        //public DateTime? FEEExitsSite { get; set; }

        [Display(Name = "Logg")]
        public string Logg { get; set; }
        //[Display(Name = "WLs #")]
        //public int? PurchaseOrderId { get; set; }
        //[Display(Name = "WLs #")]
        //[ForeignKey("PurchaseOrderId")]
        //public PurchaseOrder PurchaseOrder { get; set; }



        //Incident Resolution
        [Display(Name = "Resolved")]
        public DateTime? IssueResolved { get; set; }


        [Display(Name = "Resolution")]
        public string Resolution { get; set; }

        // PO (Purchase Order)

        [Display(Name = "PO #")]
        public int? PurchaseOrderId { get; set; }
        [Display(Name = "PO #")]
        [ForeignKey("PurchaseOrderId")]
        public PurchaseOrder PurchaseOrder { get; set; }

        //Reporting to accounting
        //When Status = Resolved then build an IncidentReport !
    }
}

Models/DataModels/IncidentType.cs
using System.ComponentModel.DataAnnotations;

namespace TicketHandler.Models.DataModels
{
    public class IncidentType
    {
        public int Id { get; set; }

        [Display(Name = "Type")]
        public string IncidentTypeName { get; set; }
    }
}

Controllers/IncidentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TicketHandler.Data;
using TicketHandler.Models.DataModels;
using TicketHandler.Models.ViewModels;

namespace TicketHandler.Controllers
{
    public class IncidentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public IncidentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Incidents
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Incident
                .Include(i => i.Creator)
                .Include(i => i.FEAssigned)
                .Include(i => i.IncidentPriority)
                .Include(i => i.IncidentStatus)
                .Include(i => i.IncidentType)
                .Include(i => i.PurchaseOrder)
                .Include(i => i.Receiver)
                .Include(i => i.Site);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: ListIncidents
        public IActionResult ListIncidents()
        {
            var dataViewModel = new DataViewModel()
            {
                Incidents = _context.Incident
                .Include(i => i.Creator)
                .Include(i => i.FEAssigned)
                .Include(i => i.IncidentPriority)
                .Include(i => i.IncidentStatus)
                .Include(i => i.IncidentType)
                .Include(i => i.Receiver)
                .Include(i => i.Site)
                .Include(i => i.PurchaseOrder)
                .ToList()
            };
            return View(dataViewModel);
        }

            // GET: Incidents/Details/5
            public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var incident = await _context.Incident
                .Include(i => i.Creator)
                .Include(i => i.FEAssigned)
                .Include(i => i.IncidentPriority)
                .Include(i => i.IncidentStatus)
                .Include(i => i.IncidentType)
                .Include(i => i.PurchaseOrder)
                .Include(i => i.Receiver)
                .Include(i => i.Site)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (incident == null)
            {
                return NotFound();
            }

            return View(incident);
        }

        // GET: Incidents/Create
        public IActionResult Create()
        {
            ViewData["PersonId"] = new SelectList(_context.Set<Person>(), "Id", "FullName");
            ViewData["PersonId2"] = new SelectList(_context.Set<Person>(), "Id", "FullName");
            ViewData["IncidentPriorityId"] = new SelectList(_context.Set<IncidentPriority>(), "Id", "IncidentPriorityName");
            ViewData["IncidentStatusId"] = new SelectList(_context.Set<IncidentStatus>(), "Id", "IncidentStatusName");
            ViewData["IncidentTypeId"] = new SelectList(_context.Set<IncidentType>(), "Id", "IncidentTypeName");
            ViewData["PurchaseOrderId"] = new SelectList(_context.Set<PurchaseOrder>(), "Id", "PONumber");
            ViewData["PersonId1"] = new SelectList(_context.Set<Person>(), "Id", "FullName");
            ViewData["SiteId"] = new SelectList(_context.Set<Site>(), "Id", "NoSite");
            return View();
        }

        // POST: Incidents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,IncidentPriorityId,IncidentStatusId,IncidentTypeId,IncidentNumber,Created,PersonId,SiteId,Received,PersonId1,FEScheduled,PersonId2,Description,Logg,IssueResolved,Resolution,PurchaseOrderId")] Incident incident)
        {
            if (ModelState.IsValid)
            {
                _context.Add(incident);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(ListIncidents));
            }
            ViewData["PersonId"] = new SelectList(_context.Set<Person>(), "Id", "FullName", incident.PersonId);
            ViewData["PersonId2"] = new SelectList(_context.Set<Person>(), "Id", "FullName", incident.PersonId2);
            ViewData["IncidentPriorityId"] = new SelectList(_context.Set<IncidentPriority>(), "Id", "IncidentPriorityName", incident.IncidentPriorityId);
            ViewData["IncidentStatusId"] = new SelectList(_context.Set<IncidentStatus>(), "Id", "IncidentPriorityName", incident.IncidentStatusId);
            ViewData["IncidentTypeId"] = new SelectList(_context.Set<IncidentType>(), "Id", "IncidentTypeName", incident.IncidentTypeId);
            ViewData["PurchaseOrderId"] = new SelectList(_context.Set<PurchaseOrder>(), "Id", "PONumber", incident.PurchaseOrderId);
            ViewData["PersonId1"] = new SelectList(_context.Set<Person>(), "Id", "FullName", incident.PersonId1);
            ViewData["SiteId"] = new SelectList(_context.Set<Site>(), "Id", "NoSite", incident.SiteId);
            return View(incident);
        }

        // GET: Incidents/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var incident = await _context.Incident.FindAsync(id);
            if (incident == null)
            {
                return NotFound();
            }
            ViewData["PersonId"] = new SelectList(_context.Set<Person>(), "Id", "FullName", incident.PersonId);
            ViewData["PersonId2"] = new SelectList(_context.Set<Person>(), "Id", "FullName", incident.PersonId2);
            ViewData["IncidentPriorityId"] = new SelectList(_context.Set<IncidentPriority>(), "Id", "IncidentPriorityName", incident.IncidentPriorityId);
            ViewData["IncidentStatusId"] = new SelectList(_context.Set<IncidentStatus>(), "Id", "IncidentPriorityName", incident.IncidentStatusId);
            ViewData["IncidentTypeId"] = new SelectList(_context.Set<IncidentType>(), "Id", "IncidentTypeName", incident.IncidentTypeId);
            ViewData["PurchaseOrderId"] = new SelectList(_context.Set<PurchaseOrder>(), "Id", "PONumber", incident.PurchaseOrderId);
            ViewData["PersonId1"] = new SelectList(_context.Set<Person>(), "Id", "FullName", incident.PersonId1);
            ViewData["SiteId"] = new SelectList(_context.Set<Site>(), "Id", "NoSite", incident.SiteId);
            return View(incident);
        }

        // POST: Incidents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,IncidentPriorityId,IncidentStatusId,IncidentTypeId,IncidentNumber,Created,PersonId,SiteId,Received,PersonId1,FEScheduled,PersonId2,Description,Logg,IssueResolved,Resolution,PurchaseOrderId")] Incident incident)
        {
            if (id != incident.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(incident);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IncidentExists(incident.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(ListIncidents));
            }
            ViewData["PersonId"] = new SelectList(_context.Set<Person>(), "Id", "FullName", incident.PersonId);
            ViewData["PersonId2"] = new SelectList(_context.Set<Person>(), "Id", "FullName", incident.PersonId2);
            ViewData["IncidentPriorityId"] = new SelectList(_context.Set<IncidentPriority>(), "Id", "IncidentPriorityName", incident.IncidentPriorityId);
            ViewData["IncidentStatusId"] = new SelectList(_context.Set<IncidentStatus>(), "Id", "IncidentPriorityName", incident.IncidentStatusId);
            ViewData["IncidentTypeId"] = new SelectList(_context.Set<IncidentType>(), "Id", "IncidentTypeName", incident.IncidentTypeId);
            ViewData["PurchaseOrderId"] = new SelectList(_context.Set<PurchaseOrder>(), "Id", "PONumber", incident.PurchaseOrderId);
            ViewData["PersonId1"] = new SelectList(_context.Set<Person>(), "Id", "FullName", incident.PersonId1);
            ViewData["SiteId"] = new SelectList(_context.Set<Site>(), "Id", "NoSite", incident.SiteId);
            return View(incident);
        }

        // GET: Incidents/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var incident = await _context.Incident
                .Include(i => i.Creator)
                .Include(i => i.FEAssigned)
                .Include(i => i.IncidentPriority)
                .Include(i => i.IncidentStatus)
                .Include(i => i.IncidentType)
                .Include(i => i.PurchaseOrder)
                .Include(i => i.Receiver)
                .Include(i => i.Site)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (incident == null)
            {
                return NotFound();
            }

            return View(incident);
        }

        // POST: Incidents/Delete/5

Views/Incidents/Create.cshtml
@model TicketHandler.Models.DataModels.Incident

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Incident</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IncidentPriorityId" class="control-label"></label>
                <select asp-for="IncidentPriorityId" class ="form-control" asp-items="ViewBag.IncidentPriorityId"></select>
            </div>
            <div class="form-group">
                <label asp-for="IncidentStatusId" class="control-label"></label>
                <select asp-for="IncidentStatusId" class ="form-control" asp-items="ViewBag.IncidentStatusId"></select>
            </div>
            <div class="form-group">
                <label asp-for="IncidentTypeId" class="control-label"></label>
                <select asp-for="IncidentTypeId" class ="form-control" asp-items="ViewBag.IncidentTypeId"></select>
            </div>
            <div class="form-group">
                <label asp-for="IncidentNumber" class="control-label"></label>
                <input asp-for="IncidentNumber" class="form-control" />
                <span asp-validation-for="IncidentNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Created" class="control-label"></label>
                <input asp-for="Created" class="form-control" />
                <span asp-validation-for="Created" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PersonId" class="control-label"></label>
                <select asp-for="PersonId" class ="form-control" asp-items="ViewBag.PersonId"></select>
            </div>
            <div class="form-group">
                <label asp-for="SiteId" class="control-label"></label>
                <select asp-for="SiteId" class ="form-control" asp-items="ViewBag.SiteId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Received" class="control-label"></label>
                <input asp-for="Received" class="form-control" />
                <span asp-validation-for="Received" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PersonId1" class="control-label"></label>
                <select asp-for="PersonId1" class ="form-control" asp-items="ViewBag.PersonId1"></select>
            </div>
            <div class="form-group">
                <label asp-for="FEScheduled" class="control-label"></label>
                <input asp-for="FEScheduled" class="form-control" />
                <span asp-validation-for="FEScheduled" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PersonId2" class="control-label"></label>
                <select asp-for="PersonId2" class ="form-control" asp-items="ViewBag.PersonId2"></select>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Logg" class="control-label"></label>
                <input asp-for="Logg" class="form-control" />
                <span asp-validation-for="Logg" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IssueResolved" class="control-label"></label>
                <input asp-for="IssueResolved" class="form-control" />
                <span asp-validation-for="IssueResolved" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Resolution" class="control-label"></label>
                <input asp-for="Resolution" class="form-control" />
                <span asp-validation-for="Resolution" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PurchaseOrderId" class="control-label"></label>
                <select asp-for="PurchaseOrderId" class ="form-control" asp-items="ViewBag.PurchaseOrderId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Incidents/Delete.cshtml
@model TicketHandler.Models.DataModels.Incident

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Incident</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IncidentPriority)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IncidentPriority.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IncidentStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IncidentStatus.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IncidentType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IncidentType.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IncidentNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IncidentNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Creator)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Creator.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Site)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Site.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Received)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Received)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Receiver)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Receiver.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FEScheduled)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FEScheduled)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FEAssigned)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FEAssigned.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Logg)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Logg)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IssueResolved)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IssueResolved)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Resolution)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Resolution)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PurchaseOrder)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PurchaseOrder.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Incidents/Details.cshtml
@model TicketHandler.Models.DataModels.Incident

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Incident</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IncidentPriority)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IncidentPriority.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IncidentStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IncidentStatus.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IncidentType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IncidentType.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IncidentNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IncidentNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Creator)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Creator.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Site)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Site.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Received)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Received)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Receiver)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Receiver.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FEScheduled)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FEScheduled)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FEAssigned)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FEAssigned.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Logg)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Logg)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IssueResolved)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IssueResolved)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Resolution)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Resolution)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PurchaseOrder)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PurchaseOrder.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Incidents/ListIncidents.cshtml
@model TicketHandler.Models.ViewModels.DataViewModel
@{
    ViewData["Title"] = "ListIncidents";
}

<h1>Incidents - All</h1>

<a class="btn btn-sm btn-success" asp-controller="Incidents" asp-action="Create">Create new Incident</a>
<a class="btn btn-sm btn-success" asp-controller="Home" asp-action="Incidents">Back to Incidents</a>
<a class="btn btn-sm btn-success" asp-controller="Home" asp-action="Reporting">Back to Reporting</a>

<div class="badge">
    <table class="table table-responsive-sm table-striped">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Incidents[0].Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Incidents[0].IncidentPriority)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Incidents[0].IncidentNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Incidents[0].Site)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Incidents[0].Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Incidents[0].IncidentType)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Incidents[0].PurchaseOrder)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Incidents[0].IncidentStatus)
                </th>

                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Incidents.OrderBy(i => i.IncidentPriority.IncidentPriorityName))
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IncidentPriority.IncidentPriorityName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IncidentNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Site.NoSite)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IncidentType.IncidentTypeName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PurchaseOrder.PONumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IncidentStatus.IncidentStatusName)
                    </td>

                    <td>
                        <a class="btn btn-sm btn-success" asp-controller="Incidents" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                        <a class="btn btn-sm btn-success" asp-controller="Incidents" asp-action="Details" asp-route-id="@item.Id">Details</a>
                        <a class="btn btn-sm btn-danger" asp-controller="Incidents" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>	